inicio
enteronum1:=10;
enteronum2:=5;
decimalresultado:=1.5;
booleanoesMayor;
resultado:=num1+num2;
si(num1>num2)entonces
esMayor:=verdadero;
fin
parai:=1hasta5hacer
resultado:=resultado*i;
fin
mientras(num1>0)hacer
num1:=num1-1;
fin
LimpiarPantalla();
Escribir("Resultado:",resultado);
Leer(num2);
fin
